name: Iris Codec WASM Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git \
            ${{ github.workspace }}/emsdk
          cd ${{ github.workspace }}/emsdk
          git pull
          ./emsdk  install latest
          ./emsdk activate latest
        shell: bash

      - name: Configure & Build
        working-directory: javascript
        run: |
          source ${{ github.workspace }}/emsdk/emsdk_env.sh
          emcmake cmake -B build -DCMAKE_INSTALL_PREFIX=install .
          cmake --build build --config Release -j$CPU_COUNT
          cmake --install build
        shell: bash

      - name: Package Artifact
        working-directory: javascript
        run: |
          tar -czf iris-codec-javascript.tar.gz -C install .

      - name: Upload WASM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: javascript
          path: javascript/iris-codec-javascript.tar.gz
