name: Iris Codec Linux CMake CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*/README.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '*/README.md'

jobs:
  build:
    strategy: 
      fail-fast: false

      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        build_type: [Release]
        c_compiler: [clang, gcc]
      
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-latest
            name: ubuntu
            arch: aarch64
          - os: ubuntu-24.04-arm
            name: ubuntu
            arch: amd64
    uses: ./.github/workflows/build-linux.yml
    with: 
      os: ${{ matrix.os }}
      c_compiler: ${{ matrix.c_compiler }}
      cpp_compiler: ${{ matrix.cpp_compiler }}
      build_type: ${{ matrix.build_type }}
      artifact: ${{ matrix.name }}-${{ matrix.arch }}-${{ matrix.c_compiler }}
      iris_cmake_flags: >
        -D IRIS_BUILD_PYTHON=ON
      


      